### ISSUE TITLE
Visual Studio 2019 Support

### ISSUE THREAD

**Issue by Myster** [madskristensen/BrowserLinkInspector#7]
I would love for this Extension to work with vs2019.

I recently upgraded and found myself constantly pressing the inspect key combination in my browser and then feeling sad ;-) 

There is a similar [issue against WebEssentials2019](https://github.com/madskristensen/WebEssentials2019/issues/2), but this repo seems the best place for this feature request so I've created this issue.

**Comment by datamill2015** [comment]
Mads,
We really need support for this extension in vs2019. I don't know how anyone can live without it. Tim Mulholland from MSFT Developer Community did a great job in providing a VS2019 fix that actually worked and reportedly sent it over to you for finishing up but nothing is available yet. I know that you were out for a few weeks at the time at Inspire 2019 and now the holidays. If I knew whatr I was doing I would be happy to conribute a fix, but I don't. PLEASE consider wrapping this up. You have created WONDERFUL tools and the community has come to rely on them -- and YOU. Please do what you can. Please feel free to contact me if you think there is anything that I can do to help push this through. Thanks, Mads!

**Comment by madskristensen** [comment]
I have to create a new extension targeted specifically at VS2019. That is the problem. Once you add support for VS2019 then you automatically drop it for vS2017. It's just a little more work, and that is why I haven't gotten to it yet.

/cc @timheuer

**Comment by datamill2015** [comment]
Mads, Thanks for your kind and quick reply. I do understand. If I can do anything to help, please let me know. We ALL appreciate the fine work that you do to help the community. I'll keep my fingers crossed. :-)  Thanks again. - RJ

**Comment by CatalinRadoi** [comment]
Go Mads! :)

**Comment by RJMJII** [comment]
Hi Mads... Just checking in to see if there has been any progress or if this project has an anticipated date. I'm being terribly selfish here, but this extension is SO time-saving for anyone with a web project that it's killing me without it. I think I speak for many others too. Is there anything that we as the community could do to help move this forward? I know that you have a full plate so anything you could do would be SO appreciated. Thank you, Mads!

**Comment by madskristensen** [comment]
Please help test [CI build](https://www.vsixgallery.com/extension/e607008b-f079-4e79-8d23-1d8c5dba1626) of **Browser Link Inspector 2019** before I publish it to the Marketplace.

**Comment by RJMJII** [comment]
Attempted to install but VS2019 Professional greyed out: "The extension cannot be installed to this product due to prerequisites that cannot be resolved." Any thoughts?

**Comment by Myster** [comment]
I get the same. 
![image](https://user-images.githubusercontent.com/354777/83987302-de1dc100-a993-11ea-9ea0-3c8b31bb6ac9.png)

**Comment by madskristensen** [comment]
Thanks for testing. I've fixed the issue. Grab the latest version on the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.BrowserLinkInspector2019)

**Comment by RJMJII** [comment]
Hey Mads,

First, thanks so much for attempting to get this running. It's a life saver when needed. Really -- thanks.

I've managed to install the extension (Win 10, VS2019 Pro V16.6.1, Chrome 83.0.4103.97 - also tried Chrome Beta and MS Edge). I am still unable to get it to work. With OR without the Chrome extension in Chrome, inspect or design mode first display the __browserLink_InspectOverlay (the display lightens a touch) and also displays the "crosshair" icon when starting with Ctrl+Alt+I or Ctrl+Alt+D respectively, or from the BrowserLink Dashboard. But that is , unfortunately, where the functionality stops.

Has anyone else been successful with running this? If so - I will investigate further on my end but nothing is apparent that would be causing conflict.

Thanks, Mads.

RJ

**Comment by madskristensen** [comment]
I've seen it being a little slow to open and select the ranges in Visual Studio when you inspect in the browser. Can you see if it just takes longer than normal?

**Comment by RJMJII** [comment]
I think that I may see a delay that you may be speaking of, but it still doesn’t work beyond what I’ve already expressed. To the point of the “delay”, upon clicking “Refresh” on the BrowserLink Dashboard, a second Connection appears and it takes about 10-11 seconds for the old connection to disappear. I have a pretty fast machine, so I don’t think that it is hardware related. Is that related to any delay that you were speaking of? I’ve rebooted (for giggles) and could reinstall Web Essentials if you think that could be helpful. Results are the same with/without the Chrome Web Essentials extension.

**Comment by madskristensen** [comment]
@RJMJII the second connection that shows up after refreshing, is that caused by the extension?

**Comment by RJMJII** [comment]
To be clear, I would assume that it is caused by the VSIX Browser extension, as opposed to the Chrome Extension, as I deactivated the Chrome extension and it still happens. But, like I said, it disappears after about 10-11 seconds. If I F5 a few times in the browser, I will get another "instance" listed on the Browser Extension Dashboard for each press of F5, then they disappear with a second or so of each other. I can supply a gif if you like. 

Update, however -- some good news. I seem to recall this from a long time ago. SOOO -- 
BrowserLinkInspector2019 DOES work for a top-level domain (e.g. example.com vs a subdomain m.example.com). We use m.example.com for the mobile version of our clients' sites. Regardless of how I configure the "project" page - like m.example.com as the project URL -- BLI only works if the the project URL is set to example.com. If my recollection serves me correctly, I had been able to get around this by setting the project URL to m.example.com in order to debug the mobile version. Without being able to debug m.example.com I am stuck in the mud again. :-(

**Comment by RJMJII** [comment]
After a couple of days of changing and testing to try to get **m.example.dev** (the project URL) working with Browser Link Inspector 2019 (BLI2017), I reinstalled VS2017 and BLI2017 extension. I had recently migrated to a new machine and hadn't needed a previous VS version before, so this was a new install of VS2017. So now I start up VS2017 on the same machine that VS2019 is running, copy the complete solution and run (debug) the copied solution in VS2017 and voila! BLI**2017** works -- so there must STILL be a bug in BLI**2019** with handling a subdomain as a project URL.

This is BLI**2017** on my current (new) machine using a copy of the solution and m.example.dev as a subdomain. It performs as expected:
![BrowserLink2017Example](https://user-images.githubusercontent.com/61396899/84416802-5249a600-abda-11ea-803a-0a7dfbc6ada9.gif)

BLI2019 works as above if a NON-subdomain is used as project URL, but when a subdomain is used and BLI is invoked, the crosshair appears, the elements lighten, but no rectangles appear on hover and nothing happens on click.

Mads: Is there a chance that you could look at this to see if there is something bugging BLI2019? I've spent many hours testing and making sure that the fault is not mine. We all appreciate all your time and hard work that goes into creating these extensions that we sometimes take for granted.
